# NumPy

In [1]:
import numpy as np

## 1. Creation of a 1-D array

In [10]:
# Array with values from from 2 to 50 with step size 3
a = np.arange(2,51,3)
print(a)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


## 2. Array from lists + array operations

In [34]:
list_a = [int(i) for i in input().split()]
list_b = [int(i) for i in input().split()]
array_a = np.array(list_a)
array_b = np.array(list_b)
print(array_a)
print(array_b)
# Concatenation
merged = np.concatenate([array_a,array_b])
print(merged)
# Sorting
sorted = np.sort(merged)
print(sorted)

4 7 8
3 2 1
[4 7 8]
[3 2 1]
[4 7 8 3 2 1]
[1 2 3 4 7 8]


## 3. Dimensions and size of an ndarray

In [37]:
a = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]]]) # 3-D array
print(a)
print(a.ndim)
print(a.size)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
3
18


## 4. Convert 1-D to 2-D array

In [49]:
a = np.arange(9) # 1-D array
print(a,a.shape)
b = a[np.newaxis,:] # Converted to 2-D array with single row
print(b,b.shape)
c = np.expand_dims(a,1) # Converted to 2-D array with single column
print(c,c.shape)

[0 1 2 3 4 5 6 7 8] (9,)
[[0 1 2 3 4 5 6 7 8]] (1, 9)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]] (9, 1)


## 5. Stacking arrays

In [60]:
a = np.identity(3,int)
b = np.identity(3,int)
print(a)
print(b)
print(np.hstack([a,b])) # Print horizontally stacked arrays
print(np.vstack([a,b])) # Print vertically stacked arrays


[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 1 0 0]
 [0 1 0 0 1 0]
 [0 0 1 0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]


## 6. Unique elements of array

In [76]:
a = np.random.randint(0,10,50) # Generate test array of 50 random digits
print(a)
u,u_counts = np.unique(a,return_counts=True) # Produce array of unique values and their counts
for i in range(len(u)):
    print(u[i],':',u_counts[i])

[6 0 0 0 7 7 9 0 3 4 2 8 7 2 5 1 4 0 6 3 9 4 7 0 9 8 0 2 4 5 1 2 4 5 5 1 7
 5 6 3 5 8 3 2 1 5 5 8 0 1]
0 : 8
1 : 5
2 : 5
3 : 4
4 : 5
5 : 8
6 : 3
7 : 5
8 : 4
9 : 3
